language: python

sudo: true

python:
  - 2.7
  - 3.6
  - 3.7-dev

addons:
    apt:
        sources:
            - debian-sid

before_install:
  - sudo apt-get update
  - sudo apt-get install cython python-dev
  - sudo apt-get install libflint-dev
  - wget https://github.com/fredrik-johansson/arb/archive/2.15.0.tar.gz
  - mv 2.15.0.tar.gz arb-2.15.0.tar.gz
  - tar -xf arb-2.15.0.tar.gz
  - cd arb-2.15.0
  - ./configure --disable-static
  - make -j4 > /dev/null 2>&1
  - sudo make install
  - cd ..

install:
  - python setup.py build_ext
  - sudo python setup.py install

script:
  - python test/test.py
