name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-20.04, windows-2019, macOS-10.15]
        os: [ubuntu-20.04, macOS-10.15]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_BUILD: cp37-* cp38-* cp39-* cp310-*
          CIBW_SKIP: "*-win32 *-manylinux_i686 *-musllinux_*"
          CIBW_BEFORE_ALL_LINUX: bin/cibw_before_build_linux.sh
          CIBW_BEFORE_ALL_MACOS: bin/cibw_before_build_macosx.sh
          CIBW_BEFORE_BUILD: pip install numpy cython
          CIBW_ENVIRONMENT: >
            C_INCLUDE_PATH=$(pwd)/.local/include/
            LIBRARY_PATH=$(pwd)/.local/lib/
            LD_LIBRARY_PATH=$(pwd)/.local/lib:$LD_LIBRARY_PATH
          CIBW_TEST_COMMAND: "python -c \'import flint; assert str(flint.fmpq(3, 2)**2) == \"9/4\"\'"

      - uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl
