name: Build Test

on: [push, pull_request]

jobs:

  build_test:
    name: Build with flint ${{ matrix.flintver }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # All supported versions
        flintver: ['3.0.0', '3.0.1', '3.1.0']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: bin/build_install.sh ${{ matrix.flintver }}
      - run: python -m flint.test
